name: Automate Nodejs Application to my Server Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 20m
          # protocol: tcp4
          script: |
            cd /home/baki/NotesmanAI
            git pull
            docker compose up --build -d
            docker compose exec -T nginx nginx -s reload

